[package]
name = "iota-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]      # Creates dynamic lib

[dependencies]
futures =  { version = "0.3.17", default-features = false }
iota-wallet = { path = "../../", version = "1.0.0-beta.1", features = ["message_interface", "events"] }
once_cell = { version = "1.8.0", default-features = false }
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false }
tokio = { version = "1.12.0", default-features = false}
