name: Deploy Rust Docs to GH pages

on: workflow_dispatch


jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy Rust Docs
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev
          DOCFLAGS="--cfg docsrs" cargo +stable doc --all-features --document-private-items --no-deps --release
          mkdir -p ./documentation/build/rust
      - name: Release to GitHub Pages
        uses: iotaledger/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          cname: wallet-lib.docs.iota.org
