name: Build python binding wheels

on:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/python_binding_publish.yml
      - bindings/python/**
      - src/**
      - Cargo.lock
      - Cargo.toml

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        python-version: [3.10]
        include:
          - os: ubuntu-latest
            identifier: linux
            python: python3
          - os: macos-latest
            identifier: macos
            python: python3
          - os: windows-latest
            identifier: windows
            python: python

    steps:
     - uses: actions/checkout@v3

     - name: Install LLVM and Clang (Windows) # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
       uses: KyleMayes/install-llvm-action@32c4866ebb71e0949e8833eb49beeebed48532bd
       if: matrix.os == 'windows-latest'
       with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm
      
     - name: Set LIBCLANG_PATH (Windows)
       run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
       if: matrix.os == 'windows-latest'

     - uses: actions-rs/toolchain@v1
       with:
         toolchain: stable
         override: true
         profile: minimal

     - uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}

     - name: Install required packages (Ubuntu)
       if: matrix.os == 'ubuntu-latest'
       run: |
         sudo apt-get update
         sudo apt-get install libudev-dev libusb-1.0-0-dev

     - name: Build wheels
       working-directory: bindings/python/native
       run: |
         ${{ matrix.python }} -m pip install -Iv maturin==0.9.4
         maturin build --release --manylinux off

     - uses: actions/upload-artifact@v2
       with:
         name: ${{ matrix.identifier }}-iota-wallet-py${{ matrix.python-version }}-wheel
         path: bindings/python/native/target/wheels/
